apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: xdql32r1l-python 
  janus-idp.io/tekton: xdql32r1l-python
  backstage.io/kubernetes-id: xdql32r1l-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xdql32r1l-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml